export const storePageSelectors = {
  sizeFilterMenu: "h4.sc-bj2vay-2",
  sizeXS: "input[data-testid='checkbox'][value='XS'] + .checkmark",
  sizeML: "input[data-testid='checkbox'][value='ML'] + .checkmark",
  productGrid: "div.sc-uhudcz-0 > div[tabindex='1']",
  productCount: "#root > div > main > main > main",
  addblueTShirtbtn: "//*[@id='root']/div/main/main/div/div[6]/button",
  addblackTShirtWhiteStripesbtn: "//*[@id='root']/div/main/main/div/div[10]/button",
  cartIconbtn: "//*[@id='root']/div/div/button",
  cartPanel: "//*[@id='root']/div/div/div",
  cartItemsDistinct: "div.sc-7th5t8-0 > div.sc-11uohgb-0",
  cartItems: "//*[@id='root']/div/div/div/div[1]/div/div",
  cartItemsname: "div.sc-7th5t8-0 div.sc-11uohgb-1 p.sc-11uohgb-2",
  productPrice:"div.sc-11uohgb-0 div.sc-11uohgb-4 p",
  increaseQuantityButton: "//*[@id='root']/div/div/div/div[2]/div[1]/div[2]/div/button[2]",
  cartSubtotal: "//*[@id='root']/div/div/div/div[3]/div/p[1]",
  removeItemButton: "button[title='remove product from cart']",
  emptyCartMessage: "//*[@id='root']/div/div/div/div[2]/p",
};